// generated by compile -asmhdr from package neragogearing

#define const_AAA 0
#define const_BBB 1
#define const_CCC 2
#define TestItem__size 8
#define TestItem_id 0
#define TestItem_value 4
#define TestItem2__size 8
#define TestItem2_TestItem 0
#define TestMe__size 32
#define TestMe_blah 0
#define TestMe_list 8
