// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: multi.proto

package gearproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiSetJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimRunSize    int32                  `protobuf:"varint,1,opt,name=simRunSize,proto3" json:"simRunSize,omitempty"`
	Param         []*MultiSetParam       `protobuf:"bytes,2,rep,name=param,proto3" json:"param,omitempty"`
	FixedForge    []*FixedForge          `protobuf:"bytes,3,rep,name=fixed_forge,json=fixedForge,proto3" json:"fixed_forge,omitempty"`
	UsageGroups   []*DistinctUsageGroups `protobuf:"bytes,4,rep,name=usage_groups,json=usageGroups,proto3" json:"usage_groups,omitempty"`
	BagsFile      string                 `protobuf:"bytes,5,opt,name=bagsFile,proto3" json:"bagsFile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiSetJob) Reset() {
	*x = MultiSetJob{}
	mi := &file_multi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSetJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSetJob) ProtoMessage() {}

func (x *MultiSetJob) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSetJob.ProtoReflect.Descriptor instead.
func (*MultiSetJob) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{0}
}

func (x *MultiSetJob) GetSimRunSize() int32 {
	if x != nil {
		return x.SimRunSize
	}
	return 0
}

func (x *MultiSetJob) GetParam() []*MultiSetParam {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *MultiSetJob) GetFixedForge() []*FixedForge {
	if x != nil {
		return x.FixedForge
	}
	return nil
}

func (x *MultiSetJob) GetUsageGroups() []*DistinctUsageGroups {
	if x != nil {
		return x.UsageGroups
	}
	return nil
}

func (x *MultiSetJob) GetBagsFile() string {
	if x != nil {
		return x.BagsFile
	}
	return ""
}

type MultiSetParam struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Label                     string                 `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	GearFile                  string                 `protobuf:"bytes,2,opt,name=GearFile,proto3" json:"GearFile,omitempty"`
	Model                     *Model                 `protobuf:"bytes,3,opt,name=Model,proto3" json:"Model,omitempty"`
	RatingPercent             float64                `protobuf:"fixed64,4,opt,name=RatingPercent,proto3" json:"RatingPercent,omitempty"`
	ExtraUpgradeLevel         int32                  `protobuf:"varint,6,opt,name=ExtraUpgradeLevel,proto3" json:"ExtraUpgradeLevel,omitempty"`
	ForceUpgradeExistingItems int32                  `protobuf:"varint,7,opt,name=ForceUpgradeExistingItems,proto3" json:"ForceUpgradeExistingItems,omitempty"`
	ExtraFromBags             bool                   `protobuf:"varint,8,opt,name=ExtraFromBags,proto3" json:"ExtraFromBags,omitempty"`
	ExtraItems                []uint32               `protobuf:"varint,9,rep,packed,name=ExtraItems,proto3" json:"ExtraItems,omitempty"`
	BlockedItems              []uint32               `protobuf:"varint,10,rep,packed,name=BlockedItems,proto3" json:"BlockedItems,omitempty"`
	ForceSingle               []*ItemInSlot          `protobuf:"bytes,11,rep,name=ForceSingle,proto3" json:"ForceSingle,omitempty"`
	ForceTryAll               []*ItemListInSlot      `protobuf:"bytes,12,rep,name=ForceTryAll,proto3" json:"ForceTryAll,omitempty"`
	ReportVariant             *ItemInSlot            `protobuf:"bytes,13,opt,name=ReportVariant,proto3" json:"ReportVariant,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *MultiSetParam) Reset() {
	*x = MultiSetParam{}
	mi := &file_multi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiSetParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSetParam) ProtoMessage() {}

func (x *MultiSetParam) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSetParam.ProtoReflect.Descriptor instead.
func (*MultiSetParam) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{1}
}

func (x *MultiSetParam) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *MultiSetParam) GetGearFile() string {
	if x != nil {
		return x.GearFile
	}
	return ""
}

func (x *MultiSetParam) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *MultiSetParam) GetRatingPercent() float64 {
	if x != nil {
		return x.RatingPercent
	}
	return 0
}

func (x *MultiSetParam) GetExtraUpgradeLevel() int32 {
	if x != nil {
		return x.ExtraUpgradeLevel
	}
	return 0
}

func (x *MultiSetParam) GetForceUpgradeExistingItems() int32 {
	if x != nil {
		return x.ForceUpgradeExistingItems
	}
	return 0
}

func (x *MultiSetParam) GetExtraFromBags() bool {
	if x != nil {
		return x.ExtraFromBags
	}
	return false
}

func (x *MultiSetParam) GetExtraItems() []uint32 {
	if x != nil {
		return x.ExtraItems
	}
	return nil
}

func (x *MultiSetParam) GetBlockedItems() []uint32 {
	if x != nil {
		return x.BlockedItems
	}
	return nil
}

func (x *MultiSetParam) GetForceSingle() []*ItemInSlot {
	if x != nil {
		return x.ForceSingle
	}
	return nil
}

func (x *MultiSetParam) GetForceTryAll() []*ItemListInSlot {
	if x != nil {
		return x.ForceTryAll
	}
	return nil
}

func (x *MultiSetParam) GetReportVariant() *ItemInSlot {
	if x != nil {
		return x.ReportVariant
	}
	return nil
}

type Model struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	StatRequirements *StatRequirements      `protobuf:"bytes,1,opt,name=StatRequirements,proto3" json:"StatRequirements,omitempty"`
	StatRatings      *StatRatings           `protobuf:"bytes,2,opt,name=StatRatings,proto3" json:"StatRatings,omitempty"`
	Spec             SpecType               `protobuf:"varint,3,opt,name=Spec,proto3,enum=gearproto.SpecType" json:"Spec,omitempty"`
	Goal             OptimiseGoal           `protobuf:"varint,4,opt,name=Goal,proto3,enum=gearproto.OptimiseGoal" json:"Goal,omitempty"`
	Fight            Fight                  `protobuf:"varint,5,opt,name=Fight,proto3,enum=gearproto.Fight" json:"Fight,omitempty"`
	ReforgeRules     *ReforgeRules          `protobuf:"bytes,6,opt,name=ReforgeRules,proto3" json:"ReforgeRules,omitempty"`
	Enchant          []*Enchant             `protobuf:"bytes,7,rep,name=Enchant,proto3" json:"Enchant,omitempty"`
	Gem              []*Gem                 `protobuf:"bytes,8,rep,name=Gem,proto3" json:"Gem,omitempty"`
	Professions      *Professions           `protobuf:"bytes,9,opt,name=Professions,proto3" json:"Professions,omitempty"`
	SetBonus         *SetBonus              `protobuf:"bytes,10,opt,name=SetBonus,proto3" json:"SetBonus,omitempty"`
	SetBonusRequired uint32                 `protobuf:"varint,11,opt,name=SetBonusRequired,proto3" json:"SetBonusRequired,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_multi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{2}
}

func (x *Model) GetStatRequirements() *StatRequirements {
	if x != nil {
		return x.StatRequirements
	}
	return nil
}

func (x *Model) GetStatRatings() *StatRatings {
	if x != nil {
		return x.StatRatings
	}
	return nil
}

func (x *Model) GetSpec() SpecType {
	if x != nil {
		return x.Spec
	}
	return SpecType_SpecType_Unknown
}

func (x *Model) GetGoal() OptimiseGoal {
	if x != nil {
		return x.Goal
	}
	return OptimiseGoal_OptimiseGoal_Unknown
}

func (x *Model) GetFight() Fight {
	if x != nil {
		return x.Fight
	}
	return Fight_Fight_Unknown
}

func (x *Model) GetReforgeRules() *ReforgeRules {
	if x != nil {
		return x.ReforgeRules
	}
	return nil
}

func (x *Model) GetEnchant() []*Enchant {
	if x != nil {
		return x.Enchant
	}
	return nil
}

func (x *Model) GetGem() []*Gem {
	if x != nil {
		return x.Gem
	}
	return nil
}

func (x *Model) GetProfessions() *Professions {
	if x != nil {
		return x.Professions
	}
	return nil
}

func (x *Model) GetSetBonus() *SetBonus {
	if x != nil {
		return x.SetBonus
	}
	return nil
}

func (x *Model) GetSetBonusRequired() uint32 {
	if x != nil {
		return x.SetBonusRequired
	}
	return 0
}

type StatRequirements struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HitMin          uint32                 `protobuf:"varint,1,opt,name=hitMin,proto3" json:"hitMin,omitempty"`
	HitMax          uint32                 `protobuf:"varint,2,opt,name=hitMax,proto3" json:"hitMax,omitempty"`
	ExpMin          uint32                 `protobuf:"varint,3,opt,name=expMin,proto3" json:"expMin,omitempty"`
	ExpMax          uint32                 `protobuf:"varint,4,opt,name=expMax,proto3" json:"expMax,omitempty"`
	AdditionalStat  StatType               `protobuf:"varint,5,opt,name=additionalStat,proto3,enum=gearproto.StatType" json:"additionalStat,omitempty"`
	AdditionalValue uint32                 `protobuf:"varint,6,opt,name=additionalValue,proto3" json:"additionalValue,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatRequirements) Reset() {
	*x = StatRequirements{}
	mi := &file_multi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequirements) ProtoMessage() {}

func (x *StatRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequirements.ProtoReflect.Descriptor instead.
func (*StatRequirements) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{3}
}

func (x *StatRequirements) GetHitMin() uint32 {
	if x != nil {
		return x.HitMin
	}
	return 0
}

func (x *StatRequirements) GetHitMax() uint32 {
	if x != nil {
		return x.HitMax
	}
	return 0
}

func (x *StatRequirements) GetExpMin() uint32 {
	if x != nil {
		return x.ExpMin
	}
	return 0
}

func (x *StatRequirements) GetExpMax() uint32 {
	if x != nil {
		return x.ExpMax
	}
	return 0
}

func (x *StatRequirements) GetAdditionalStat() StatType {
	if x != nil {
		return x.AdditionalStat
	}
	return StatType_StatType_Unknown
}

func (x *StatRequirements) GetAdditionalValue() uint32 {
	if x != nil {
		return x.AdditionalValue
	}
	return 0
}

type StatRatings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// treat like a oneof, can't be due to repeated
	PawnFile      string     `protobuf:"bytes,1,opt,name=pawnFile,proto3" json:"pawnFile,omitempty"`
	Priority      []StatType `protobuf:"varint,2,rep,packed,name=priority,proto3,enum=gearproto.StatType" json:"priority,omitempty"`
	Values        *StatBlock `protobuf:"bytes,3,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRatings) Reset() {
	*x = StatRatings{}
	mi := &file_multi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRatings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRatings) ProtoMessage() {}

func (x *StatRatings) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRatings.ProtoReflect.Descriptor instead.
func (*StatRatings) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{4}
}

func (x *StatRatings) GetPawnFile() string {
	if x != nil {
		return x.PawnFile
	}
	return ""
}

func (x *StatRatings) GetPriority() []StatType {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *StatRatings) GetValues() *StatBlock {
	if x != nil {
		return x.Values
	}
	return nil
}

type ReforgeRules struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        []StatType             `protobuf:"varint,1,rep,packed,name=source,proto3,enum=gearproto.StatType" json:"source,omitempty"`
	Target        []StatType             `protobuf:"varint,2,rep,packed,name=target,proto3,enum=gearproto.StatType" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReforgeRules) Reset() {
	*x = ReforgeRules{}
	mi := &file_multi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReforgeRules) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReforgeRules) ProtoMessage() {}

func (x *ReforgeRules) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReforgeRules.ProtoReflect.Descriptor instead.
func (*ReforgeRules) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{5}
}

func (x *ReforgeRules) GetSource() []StatType {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ReforgeRules) GetTarget() []StatType {
	if x != nil {
		return x.Target
	}
	return nil
}

type Enchant struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slot  SlotItem               `protobuf:"varint,1,opt,name=slot,proto3,enum=gearproto.SlotItem" json:"slot,omitempty"`
	// Types that are valid to be assigned to Specify:
	//
	//	*Enchant_EffectId
	//	*Enchant_Name
	Specify       isEnchant_Specify `protobuf_oneof:"specify"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enchant) Reset() {
	*x = Enchant{}
	mi := &file_multi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enchant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enchant) ProtoMessage() {}

func (x *Enchant) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enchant.ProtoReflect.Descriptor instead.
func (*Enchant) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{6}
}

func (x *Enchant) GetSlot() SlotItem {
	if x != nil {
		return x.Slot
	}
	return SlotItem_SlotItem_Unknown
}

func (x *Enchant) GetSpecify() isEnchant_Specify {
	if x != nil {
		return x.Specify
	}
	return nil
}

func (x *Enchant) GetEffectId() uint32 {
	if x != nil {
		if x, ok := x.Specify.(*Enchant_EffectId); ok {
			return x.EffectId
		}
	}
	return 0
}

func (x *Enchant) GetName() string {
	if x != nil {
		if x, ok := x.Specify.(*Enchant_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isEnchant_Specify interface {
	isEnchant_Specify()
}

type Enchant_EffectId struct {
	EffectId uint32 `protobuf:"varint,2,opt,name=effectId,proto3,oneof"`
}

type Enchant_Name struct {
	Name string `protobuf:"bytes,3,opt,name=name,proto3,oneof"`
}

func (*Enchant_EffectId) isEnchant_Specify() {}

func (*Enchant_Name) isEnchant_Specify() {}

type Gem struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Socket SocketType             `protobuf:"varint,1,opt,name=socket,proto3,enum=gearproto.SocketType" json:"socket,omitempty"`
	// Types that are valid to be assigned to Specify:
	//
	//	*Gem_GemId
	//	*Gem_Stats
	Specify       isGem_Specify `protobuf_oneof:"specify"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gem) Reset() {
	*x = Gem{}
	mi := &file_multi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gem) ProtoMessage() {}

func (x *Gem) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gem.ProtoReflect.Descriptor instead.
func (*Gem) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{7}
}

func (x *Gem) GetSocket() SocketType {
	if x != nil {
		return x.Socket
	}
	return SocketType_SocketType_Unknown
}

func (x *Gem) GetSpecify() isGem_Specify {
	if x != nil {
		return x.Specify
	}
	return nil
}

func (x *Gem) GetGemId() uint32 {
	if x != nil {
		if x, ok := x.Specify.(*Gem_GemId); ok {
			return x.GemId
		}
	}
	return 0
}

func (x *Gem) GetStats() *StatBlock {
	if x != nil {
		if x, ok := x.Specify.(*Gem_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isGem_Specify interface {
	isGem_Specify()
}

type Gem_GemId struct {
	GemId uint32 `protobuf:"varint,2,opt,name=gemId,proto3,oneof"`
}

type Gem_Stats struct {
	Stats *StatBlock `protobuf:"bytes,3,opt,name=stats,proto3,oneof"`
}

func (*Gem_GemId) isGem_Specify() {}

func (*Gem_Stats) isGem_Specify() {}

type Professions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBlacksmith  bool                   `protobuf:"varint,1,opt,name=IsBlacksmith,proto3" json:"IsBlacksmith,omitempty"`
	IsEngineer    bool                   `protobuf:"varint,2,opt,name=IsEngineer,proto3" json:"IsEngineer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Professions) Reset() {
	*x = Professions{}
	mi := &file_multi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Professions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Professions) ProtoMessage() {}

func (x *Professions) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Professions.ProtoReflect.Descriptor instead.
func (*Professions) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{8}
}

func (x *Professions) GetIsBlacksmith() bool {
	if x != nil {
		return x.IsBlacksmith
	}
	return false
}

func (x *Professions) GetIsEngineer() bool {
	if x != nil {
		return x.IsEngineer
	}
	return false
}

type SetBonus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// treat like a oneof, can't be due to repeated
	None          bool     `protobuf:"varint,1,opt,name=none,proto3" json:"none,omitempty"`
	SpecDefault   bool     `protobuf:"varint,2,opt,name=specDefault,proto3" json:"specDefault,omitempty"`
	Named         []string `protobuf:"bytes,3,rep,name=named,proto3" json:"named,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBonus) Reset() {
	*x = SetBonus{}
	mi := &file_multi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBonus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBonus) ProtoMessage() {}

func (x *SetBonus) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBonus.ProtoReflect.Descriptor instead.
func (*SetBonus) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{9}
}

func (x *SetBonus) GetNone() bool {
	if x != nil {
		return x.None
	}
	return false
}

func (x *SetBonus) GetSpecDefault() bool {
	if x != nil {
		return x.SpecDefault
	}
	return false
}

func (x *SetBonus) GetNamed() []string {
	if x != nil {
		return x.Named
	}
	return nil
}

type StatBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*StatValue           `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatBlock) Reset() {
	*x = StatBlock{}
	mi := &file_multi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatBlock) ProtoMessage() {}

func (x *StatBlock) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatBlock.ProtoReflect.Descriptor instead.
func (*StatBlock) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{10}
}

func (x *StatBlock) GetValues() []*StatValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type FixedForge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Default       bool                   `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	From          StatType               `protobuf:"varint,3,opt,name=from,proto3,enum=gearproto.StatType" json:"from,omitempty"`
	To            StatType               `protobuf:"varint,4,opt,name=to,proto3,enum=gearproto.StatType" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixedForge) Reset() {
	*x = FixedForge{}
	mi := &file_multi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixedForge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixedForge) ProtoMessage() {}

func (x *FixedForge) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixedForge.ProtoReflect.Descriptor instead.
func (*FixedForge) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{11}
}

func (x *FixedForge) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *FixedForge) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *FixedForge) GetFrom() StatType {
	if x != nil {
		return x.From
	}
	return StatType_StatType_Unknown
}

func (x *FixedForge) GetTo() StatType {
	if x != nil {
		return x.To
	}
	return StatType_StatType_Unknown
}

type DistinctUsageGroups struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        uint32                 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	GroupA        []string               `protobuf:"bytes,2,rep,name=groupA,proto3" json:"groupA,omitempty"`
	GroupB        []string               `protobuf:"bytes,3,rep,name=groupB,proto3" json:"groupB,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistinctUsageGroups) Reset() {
	*x = DistinctUsageGroups{}
	mi := &file_multi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistinctUsageGroups) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistinctUsageGroups) ProtoMessage() {}

func (x *DistinctUsageGroups) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistinctUsageGroups.ProtoReflect.Descriptor instead.
func (*DistinctUsageGroups) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{12}
}

func (x *DistinctUsageGroups) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *DistinctUsageGroups) GetGroupA() []string {
	if x != nil {
		return x.GroupA
	}
	return nil
}

func (x *DistinctUsageGroups) GetGroupB() []string {
	if x != nil {
		return x.GroupB
	}
	return nil
}

type ItemInSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          SlotEquip              `protobuf:"varint,1,opt,name=slot,proto3,enum=gearproto.SlotEquip" json:"slot,omitempty"`
	ItemId        uint32                 `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemInSlot) Reset() {
	*x = ItemInSlot{}
	mi := &file_multi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemInSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInSlot) ProtoMessage() {}

func (x *ItemInSlot) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInSlot.ProtoReflect.Descriptor instead.
func (*ItemInSlot) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{13}
}

func (x *ItemInSlot) GetSlot() SlotEquip {
	if x != nil {
		return x.Slot
	}
	return SlotEquip_SlotEquip_Unknown
}

func (x *ItemInSlot) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type ItemListInSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          SlotEquip              `protobuf:"varint,1,opt,name=slot,proto3,enum=gearproto.SlotEquip" json:"slot,omitempty"`
	ItemId        []uint32               `protobuf:"varint,2,rep,packed,name=itemId,proto3" json:"itemId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemListInSlot) Reset() {
	*x = ItemListInSlot{}
	mi := &file_multi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemListInSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemListInSlot) ProtoMessage() {}

func (x *ItemListInSlot) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemListInSlot.ProtoReflect.Descriptor instead.
func (*ItemListInSlot) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{14}
}

func (x *ItemListInSlot) GetSlot() SlotEquip {
	if x != nil {
		return x.Slot
	}
	return SlotEquip_SlotEquip_Unknown
}

func (x *ItemListInSlot) GetItemId() []uint32 {
	if x != nil {
		return x.ItemId
	}
	return nil
}

type StatValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=statType,proto3,enum=gearproto.StatType" json:"statType,omitempty"`
	Value         uint32                 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatValue) Reset() {
	*x = StatValue{}
	mi := &file_multi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatValue) ProtoMessage() {}

func (x *StatValue) ProtoReflect() protoreflect.Message {
	mi := &file_multi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatValue.ProtoReflect.Descriptor instead.
func (*StatValue) Descriptor() ([]byte, []int) {
	return file_multi_proto_rawDescGZIP(), []int{15}
}

func (x *StatValue) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_StatType_Unknown
}

func (x *StatValue) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_multi_proto protoreflect.FileDescriptor

const file_multi_proto_rawDesc = "" +
	"\n" +
	"\vmulti.proto\x12\tgearproto\x1a\x11gear-common.proto\"\xf4\x01\n" +
	"\vMultiSetJob\x12\x1e\n" +
	"\n" +
	"simRunSize\x18\x01 \x01(\x05R\n" +
	"simRunSize\x12.\n" +
	"\x05param\x18\x02 \x03(\v2\x18.gearproto.MultiSetParamR\x05param\x126\n" +
	"\vfixed_forge\x18\x03 \x03(\v2\x15.gearproto.FixedForgeR\n" +
	"fixedForge\x12A\n" +
	"\fusage_groups\x18\x04 \x03(\v2\x1e.gearproto.DistinctUsageGroupsR\vusageGroups\x12\x1a\n" +
	"\bbagsFile\x18\x05 \x01(\tR\bbagsFile\"\x98\x04\n" +
	"\rMultiSetParam\x12\x14\n" +
	"\x05Label\x18\x01 \x01(\tR\x05Label\x12\x1a\n" +
	"\bGearFile\x18\x02 \x01(\tR\bGearFile\x12&\n" +
	"\x05Model\x18\x03 \x01(\v2\x10.gearproto.ModelR\x05Model\x12$\n" +
	"\rRatingPercent\x18\x04 \x01(\x01R\rRatingPercent\x12,\n" +
	"\x11ExtraUpgradeLevel\x18\x06 \x01(\x05R\x11ExtraUpgradeLevel\x12<\n" +
	"\x19ForceUpgradeExistingItems\x18\a \x01(\x05R\x19ForceUpgradeExistingItems\x12$\n" +
	"\rExtraFromBags\x18\b \x01(\bR\rExtraFromBags\x12\x1e\n" +
	"\n" +
	"ExtraItems\x18\t \x03(\rR\n" +
	"ExtraItems\x12\"\n" +
	"\fBlockedItems\x18\n" +
	" \x03(\rR\fBlockedItems\x127\n" +
	"\vForceSingle\x18\v \x03(\v2\x15.gearproto.ItemInSlotR\vForceSingle\x12;\n" +
	"\vForceTryAll\x18\f \x03(\v2\x19.gearproto.ItemListInSlotR\vForceTryAll\x12;\n" +
	"\rReportVariant\x18\r \x01(\v2\x15.gearproto.ItemInSlotR\rReportVariant\"\xac\x04\n" +
	"\x05Model\x12G\n" +
	"\x10StatRequirements\x18\x01 \x01(\v2\x1b.gearproto.StatRequirementsR\x10StatRequirements\x128\n" +
	"\vStatRatings\x18\x02 \x01(\v2\x16.gearproto.StatRatingsR\vStatRatings\x12'\n" +
	"\x04Spec\x18\x03 \x01(\x0e2\x13.gearproto.SpecTypeR\x04Spec\x12+\n" +
	"\x04Goal\x18\x04 \x01(\x0e2\x17.gearproto.OptimiseGoalR\x04Goal\x12&\n" +
	"\x05Fight\x18\x05 \x01(\x0e2\x10.gearproto.FightR\x05Fight\x12;\n" +
	"\fReforgeRules\x18\x06 \x01(\v2\x17.gearproto.ReforgeRulesR\fReforgeRules\x12,\n" +
	"\aEnchant\x18\a \x03(\v2\x12.gearproto.EnchantR\aEnchant\x12 \n" +
	"\x03Gem\x18\b \x03(\v2\x0e.gearproto.GemR\x03Gem\x128\n" +
	"\vProfessions\x18\t \x01(\v2\x16.gearproto.ProfessionsR\vProfessions\x12/\n" +
	"\bSetBonus\x18\n" +
	" \x01(\v2\x13.gearproto.SetBonusR\bSetBonus\x12*\n" +
	"\x10SetBonusRequired\x18\v \x01(\rR\x10SetBonusRequired\"\xd9\x01\n" +
	"\x10StatRequirements\x12\x16\n" +
	"\x06hitMin\x18\x01 \x01(\rR\x06hitMin\x12\x16\n" +
	"\x06hitMax\x18\x02 \x01(\rR\x06hitMax\x12\x16\n" +
	"\x06expMin\x18\x03 \x01(\rR\x06expMin\x12\x16\n" +
	"\x06expMax\x18\x04 \x01(\rR\x06expMax\x12;\n" +
	"\x0eadditionalStat\x18\x05 \x01(\x0e2\x13.gearproto.StatTypeR\x0eadditionalStat\x12(\n" +
	"\x0fadditionalValue\x18\x06 \x01(\rR\x0fadditionalValue\"\x88\x01\n" +
	"\vStatRatings\x12\x1a\n" +
	"\bpawnFile\x18\x01 \x01(\tR\bpawnFile\x12/\n" +
	"\bpriority\x18\x02 \x03(\x0e2\x13.gearproto.StatTypeR\bpriority\x12,\n" +
	"\x06values\x18\x03 \x01(\v2\x14.gearproto.StatBlockR\x06values\"h\n" +
	"\fReforgeRules\x12+\n" +
	"\x06source\x18\x01 \x03(\x0e2\x13.gearproto.StatTypeR\x06source\x12+\n" +
	"\x06target\x18\x02 \x03(\x0e2\x13.gearproto.StatTypeR\x06target\"q\n" +
	"\aEnchant\x12'\n" +
	"\x04slot\x18\x01 \x01(\x0e2\x13.gearproto.SlotItemR\x04slot\x12\x1c\n" +
	"\beffectId\x18\x02 \x01(\rH\x00R\beffectId\x12\x14\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04nameB\t\n" +
	"\aspecify\"\x85\x01\n" +
	"\x03Gem\x12-\n" +
	"\x06socket\x18\x01 \x01(\x0e2\x15.gearproto.SocketTypeR\x06socket\x12\x16\n" +
	"\x05gemId\x18\x02 \x01(\rH\x00R\x05gemId\x12,\n" +
	"\x05stats\x18\x03 \x01(\v2\x14.gearproto.StatBlockH\x00R\x05statsB\t\n" +
	"\aspecify\"Q\n" +
	"\vProfessions\x12\"\n" +
	"\fIsBlacksmith\x18\x01 \x01(\bR\fIsBlacksmith\x12\x1e\n" +
	"\n" +
	"IsEngineer\x18\x02 \x01(\bR\n" +
	"IsEngineer\"V\n" +
	"\bSetBonus\x12\x12\n" +
	"\x04none\x18\x01 \x01(\bR\x04none\x12 \n" +
	"\vspecDefault\x18\x02 \x01(\bR\vspecDefault\x12\x14\n" +
	"\x05named\x18\x03 \x03(\tR\x05named\"9\n" +
	"\tStatBlock\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.gearproto.StatValueR\x06values\"\x8c\x01\n" +
	"\n" +
	"FixedForge\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\rR\x06itemId\x12\x18\n" +
	"\adefault\x18\x02 \x01(\bR\adefault\x12'\n" +
	"\x04from\x18\x03 \x01(\x0e2\x13.gearproto.StatTypeR\x04from\x12#\n" +
	"\x02to\x18\x04 \x01(\x0e2\x13.gearproto.StatTypeR\x02to\"]\n" +
	"\x13DistinctUsageGroups\x12\x16\n" +
	"\x06itemId\x18\x01 \x01(\rR\x06itemId\x12\x16\n" +
	"\x06groupA\x18\x02 \x03(\tR\x06groupA\x12\x16\n" +
	"\x06groupB\x18\x03 \x03(\tR\x06groupB\"N\n" +
	"\n" +
	"ItemInSlot\x12(\n" +
	"\x04slot\x18\x01 \x01(\x0e2\x14.gearproto.SlotEquipR\x04slot\x12\x16\n" +
	"\x06itemId\x18\x02 \x01(\rR\x06itemId\"R\n" +
	"\x0eItemListInSlot\x12(\n" +
	"\x04slot\x18\x01 \x01(\x0e2\x14.gearproto.SlotEquipR\x04slot\x12\x16\n" +
	"\x06itemId\x18\x02 \x03(\rR\x06itemId\"R\n" +
	"\tStatValue\x12/\n" +
	"\bstatType\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05valueB\rZ\v./gearprotob\x06proto3"

var (
	file_multi_proto_rawDescOnce sync.Once
	file_multi_proto_rawDescData []byte
)

func file_multi_proto_rawDescGZIP() []byte {
	file_multi_proto_rawDescOnce.Do(func() {
		file_multi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_multi_proto_rawDesc), len(file_multi_proto_rawDesc)))
	})
	return file_multi_proto_rawDescData
}

var file_multi_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_multi_proto_goTypes = []any{
	(*MultiSetJob)(nil),         // 0: gearproto.MultiSetJob
	(*MultiSetParam)(nil),       // 1: gearproto.MultiSetParam
	(*Model)(nil),               // 2: gearproto.Model
	(*StatRequirements)(nil),    // 3: gearproto.StatRequirements
	(*StatRatings)(nil),         // 4: gearproto.StatRatings
	(*ReforgeRules)(nil),        // 5: gearproto.ReforgeRules
	(*Enchant)(nil),             // 6: gearproto.Enchant
	(*Gem)(nil),                 // 7: gearproto.Gem
	(*Professions)(nil),         // 8: gearproto.Professions
	(*SetBonus)(nil),            // 9: gearproto.SetBonus
	(*StatBlock)(nil),           // 10: gearproto.StatBlock
	(*FixedForge)(nil),          // 11: gearproto.FixedForge
	(*DistinctUsageGroups)(nil), // 12: gearproto.DistinctUsageGroups
	(*ItemInSlot)(nil),          // 13: gearproto.ItemInSlot
	(*ItemListInSlot)(nil),      // 14: gearproto.ItemListInSlot
	(*StatValue)(nil),           // 15: gearproto.StatValue
	(SpecType)(0),               // 16: gearproto.SpecType
	(OptimiseGoal)(0),           // 17: gearproto.OptimiseGoal
	(Fight)(0),                  // 18: gearproto.Fight
	(StatType)(0),               // 19: gearproto.StatType
	(SlotItem)(0),               // 20: gearproto.SlotItem
	(SocketType)(0),             // 21: gearproto.SocketType
	(SlotEquip)(0),              // 22: gearproto.SlotEquip
}
var file_multi_proto_depIdxs = []int32{
	1,  // 0: gearproto.MultiSetJob.param:type_name -> gearproto.MultiSetParam
	11, // 1: gearproto.MultiSetJob.fixed_forge:type_name -> gearproto.FixedForge
	12, // 2: gearproto.MultiSetJob.usage_groups:type_name -> gearproto.DistinctUsageGroups
	2,  // 3: gearproto.MultiSetParam.Model:type_name -> gearproto.Model
	13, // 4: gearproto.MultiSetParam.ForceSingle:type_name -> gearproto.ItemInSlot
	14, // 5: gearproto.MultiSetParam.ForceTryAll:type_name -> gearproto.ItemListInSlot
	13, // 6: gearproto.MultiSetParam.ReportVariant:type_name -> gearproto.ItemInSlot
	3,  // 7: gearproto.Model.StatRequirements:type_name -> gearproto.StatRequirements
	4,  // 8: gearproto.Model.StatRatings:type_name -> gearproto.StatRatings
	16, // 9: gearproto.Model.Spec:type_name -> gearproto.SpecType
	17, // 10: gearproto.Model.Goal:type_name -> gearproto.OptimiseGoal
	18, // 11: gearproto.Model.Fight:type_name -> gearproto.Fight
	5,  // 12: gearproto.Model.ReforgeRules:type_name -> gearproto.ReforgeRules
	6,  // 13: gearproto.Model.Enchant:type_name -> gearproto.Enchant
	7,  // 14: gearproto.Model.Gem:type_name -> gearproto.Gem
	8,  // 15: gearproto.Model.Professions:type_name -> gearproto.Professions
	9,  // 16: gearproto.Model.SetBonus:type_name -> gearproto.SetBonus
	19, // 17: gearproto.StatRequirements.additionalStat:type_name -> gearproto.StatType
	19, // 18: gearproto.StatRatings.priority:type_name -> gearproto.StatType
	10, // 19: gearproto.StatRatings.values:type_name -> gearproto.StatBlock
	19, // 20: gearproto.ReforgeRules.source:type_name -> gearproto.StatType
	19, // 21: gearproto.ReforgeRules.target:type_name -> gearproto.StatType
	20, // 22: gearproto.Enchant.slot:type_name -> gearproto.SlotItem
	21, // 23: gearproto.Gem.socket:type_name -> gearproto.SocketType
	10, // 24: gearproto.Gem.stats:type_name -> gearproto.StatBlock
	15, // 25: gearproto.StatBlock.values:type_name -> gearproto.StatValue
	19, // 26: gearproto.FixedForge.from:type_name -> gearproto.StatType
	19, // 27: gearproto.FixedForge.to:type_name -> gearproto.StatType
	22, // 28: gearproto.ItemInSlot.slot:type_name -> gearproto.SlotEquip
	22, // 29: gearproto.ItemListInSlot.slot:type_name -> gearproto.SlotEquip
	19, // 30: gearproto.StatValue.statType:type_name -> gearproto.StatType
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_multi_proto_init() }
func file_multi_proto_init() {
	if File_multi_proto != nil {
		return
	}
	file_gear_common_proto_init()
	file_multi_proto_msgTypes[6].OneofWrappers = []any{
		(*Enchant_EffectId)(nil),
		(*Enchant_Name)(nil),
	}
	file_multi_proto_msgTypes[7].OneofWrappers = []any{
		(*Gem_GemId)(nil),
		(*Gem_Stats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_multi_proto_rawDesc), len(file_multi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_multi_proto_goTypes,
		DependencyIndexes: file_multi_proto_depIdxs,
		MessageInfos:      file_multi_proto_msgTypes,
	}.Build()
	File_multi_proto = out.File
	file_multi_proto_goTypes = nil
	file_multi_proto_depIdxs = nil
}
