syntax = "proto3";
package gearproto;

option go_package = "./gearproto";

import "gear-common.proto";

message Weight1 {
  int32 weightType = 1;
  repeated StatTypeAndFloatWeight weight = 2;
  repeated SimTypeAndSimRatio priority=3;
  double scale = 4;
  double offset = 5;
}

message Weight2 {
  int32 weightType = 1;
  repeated StatSimTypesAndFloatWeight weights = 2;
  repeated SimTypeAndScaleOffsetAndSimRatio priority = 3;
}

message Weight3 {
  int32 weightType = 1;
  repeated StatSimTypesAndNestedEntries weights = 2;
  repeated SimTypeAndScaleOffsetAndSimRatio priority = 3;
}

message Weight4 {
  int32 weightType = 1;
  repeated Weight4Segment segments = 2;
  repeated SimTypeAndSimRatio priority = 3;
}

message Weight4Segment {
  repeated StatTypeAndStatRange bound = 1;
  repeated StatSimTypesAndFloatWeight weights = 2;
  repeated SimTypeAndScaleOffset offsets = 3;
}

message StatTypeAndFloatWeight {
  StatType stat_type = 1;
  double weight = 2;
}


message StatSimTypesAndFloatWeight {
  StatType stat_type = 1;
  SimType sim_type = 2;
  double weight = 3;
}

message StatSimTypesAndNestedEntries {
  StatType stat_type = 1;
  SimType sim_type = 2;
  repeated StatRangeAndWeightOffset entries = 3;
}

message StatRangeAndWeightOffset {
  uint32 stat_minimum = 1;
  uint32 stat_maximum = 2;
  double weight = 3;
  double offset = 4;
}

message StatTypeAndStatRange {
  StatType stat_type = 1;
  uint32 stat_minimum = 2;
  uint32 stat_maximum = 3;
}

message SimTypeAndSimRatio {
  SimType sim_type = 1;
  uint32 ratio_scale = 2;
}

message SimTypeAndScaleOffset {
  SimType sim_type = 1;
  double scale = 2;
  double offset = 3;
}

message SimTypeAndScaleOffsetAndSimRatio {
  SimType sim_type = 1;
  double ranging_scale = 2;
  double ranging_offset = 3;
  double ratio_scale = 4;
}

