// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: weights.proto

package gearproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Weight1 struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	WeightType    int32                     `protobuf:"varint,1,opt,name=weightType,proto3" json:"weightType,omitempty"`
	Weight        []*StatTypeAndFloatWeight `protobuf:"bytes,2,rep,name=weight,proto3" json:"weight,omitempty"`
	Priority      []*SimTypeAndSimRatio     `protobuf:"bytes,3,rep,name=priority,proto3" json:"priority,omitempty"`
	Scale         float64                   `protobuf:"fixed64,4,opt,name=scale,proto3" json:"scale,omitempty"`
	Offset        float64                   `protobuf:"fixed64,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight1) Reset() {
	*x = Weight1{}
	mi := &file_weights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight1) ProtoMessage() {}

func (x *Weight1) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight1.ProtoReflect.Descriptor instead.
func (*Weight1) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{0}
}

func (x *Weight1) GetWeightType() int32 {
	if x != nil {
		return x.WeightType
	}
	return 0
}

func (x *Weight1) GetWeight() []*StatTypeAndFloatWeight {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *Weight1) GetPriority() []*SimTypeAndSimRatio {
	if x != nil {
		return x.Priority
	}
	return nil
}

func (x *Weight1) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Weight1) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Weight2 struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	WeightType    int32                               `protobuf:"varint,1,opt,name=weightType,proto3" json:"weightType,omitempty"`
	Weights       []*StatSimTypesAndFloatWeight       `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty"`
	Priority      []*SimTypeAndScaleOffsetAndSimRatio `protobuf:"bytes,3,rep,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight2) Reset() {
	*x = Weight2{}
	mi := &file_weights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight2) ProtoMessage() {}

func (x *Weight2) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight2.ProtoReflect.Descriptor instead.
func (*Weight2) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{1}
}

func (x *Weight2) GetWeightType() int32 {
	if x != nil {
		return x.WeightType
	}
	return 0
}

func (x *Weight2) GetWeights() []*StatSimTypesAndFloatWeight {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *Weight2) GetPriority() []*SimTypeAndScaleOffsetAndSimRatio {
	if x != nil {
		return x.Priority
	}
	return nil
}

type Weight3 struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	WeightType    int32                               `protobuf:"varint,1,opt,name=weightType,proto3" json:"weightType,omitempty"`
	Weights       []*StatSimTypesAndNestedEntries     `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty"`
	Priority      []*SimTypeAndScaleOffsetAndSimRatio `protobuf:"bytes,3,rep,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight3) Reset() {
	*x = Weight3{}
	mi := &file_weights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight3) ProtoMessage() {}

func (x *Weight3) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight3.ProtoReflect.Descriptor instead.
func (*Weight3) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{2}
}

func (x *Weight3) GetWeightType() int32 {
	if x != nil {
		return x.WeightType
	}
	return 0
}

func (x *Weight3) GetWeights() []*StatSimTypesAndNestedEntries {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *Weight3) GetPriority() []*SimTypeAndScaleOffsetAndSimRatio {
	if x != nil {
		return x.Priority
	}
	return nil
}

type Weight4 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeightType    int32                  `protobuf:"varint,1,opt,name=weightType,proto3" json:"weightType,omitempty"`
	Segments      []*Weight4Segment      `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	Priority      []*SimTypeAndSimRatio  `protobuf:"bytes,3,rep,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight4) Reset() {
	*x = Weight4{}
	mi := &file_weights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight4) ProtoMessage() {}

func (x *Weight4) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight4.ProtoReflect.Descriptor instead.
func (*Weight4) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{3}
}

func (x *Weight4) GetWeightType() int32 {
	if x != nil {
		return x.WeightType
	}
	return 0
}

func (x *Weight4) GetSegments() []*Weight4Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *Weight4) GetPriority() []*SimTypeAndSimRatio {
	if x != nil {
		return x.Priority
	}
	return nil
}

type Weight4Segment struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Bound         []*StatTypeAndStatRange       `protobuf:"bytes,1,rep,name=bound,proto3" json:"bound,omitempty"`
	Weights       []*StatSimTypesAndFloatWeight `protobuf:"bytes,2,rep,name=weights,proto3" json:"weights,omitempty"`
	Offsets       []*SimTypeAndScaleOffset      `protobuf:"bytes,3,rep,name=offsets,proto3" json:"offsets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight4Segment) Reset() {
	*x = Weight4Segment{}
	mi := &file_weights_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight4Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight4Segment) ProtoMessage() {}

func (x *Weight4Segment) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight4Segment.ProtoReflect.Descriptor instead.
func (*Weight4Segment) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{4}
}

func (x *Weight4Segment) GetBound() []*StatTypeAndStatRange {
	if x != nil {
		return x.Bound
	}
	return nil
}

func (x *Weight4Segment) GetWeights() []*StatSimTypesAndFloatWeight {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *Weight4Segment) GetOffsets() []*SimTypeAndScaleOffset {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type StatTypeAndFloatWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=gearproto.StatType" json:"stat_type,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatTypeAndFloatWeight) Reset() {
	*x = StatTypeAndFloatWeight{}
	mi := &file_weights_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatTypeAndFloatWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatTypeAndFloatWeight) ProtoMessage() {}

func (x *StatTypeAndFloatWeight) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatTypeAndFloatWeight.ProtoReflect.Descriptor instead.
func (*StatTypeAndFloatWeight) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{5}
}

func (x *StatTypeAndFloatWeight) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_StatType_Unknown
}

func (x *StatTypeAndFloatWeight) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type StatSimTypesAndFloatWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=gearproto.StatType" json:"stat_type,omitempty"`
	SimType       SimType                `protobuf:"varint,2,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatSimTypesAndFloatWeight) Reset() {
	*x = StatSimTypesAndFloatWeight{}
	mi := &file_weights_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatSimTypesAndFloatWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatSimTypesAndFloatWeight) ProtoMessage() {}

func (x *StatSimTypesAndFloatWeight) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatSimTypesAndFloatWeight.ProtoReflect.Descriptor instead.
func (*StatSimTypesAndFloatWeight) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{6}
}

func (x *StatSimTypesAndFloatWeight) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_StatType_Unknown
}

func (x *StatSimTypesAndFloatWeight) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_SimType_Unknown
}

func (x *StatSimTypesAndFloatWeight) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type StatSimTypesAndNestedEntries struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	StatType      StatType                    `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=gearproto.StatType" json:"stat_type,omitempty"`
	SimType       SimType                     `protobuf:"varint,2,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	Entries       []*StatRangeAndWeightOffset `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatSimTypesAndNestedEntries) Reset() {
	*x = StatSimTypesAndNestedEntries{}
	mi := &file_weights_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatSimTypesAndNestedEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatSimTypesAndNestedEntries) ProtoMessage() {}

func (x *StatSimTypesAndNestedEntries) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatSimTypesAndNestedEntries.ProtoReflect.Descriptor instead.
func (*StatSimTypesAndNestedEntries) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{7}
}

func (x *StatSimTypesAndNestedEntries) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_StatType_Unknown
}

func (x *StatSimTypesAndNestedEntries) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_SimType_Unknown
}

func (x *StatSimTypesAndNestedEntries) GetEntries() []*StatRangeAndWeightOffset {
	if x != nil {
		return x.Entries
	}
	return nil
}

type StatRangeAndWeightOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatMinimum   uint32                 `protobuf:"varint,1,opt,name=stat_minimum,json=statMinimum,proto3" json:"stat_minimum,omitempty"`
	StatMaximum   uint32                 `protobuf:"varint,2,opt,name=stat_maximum,json=statMaximum,proto3" json:"stat_maximum,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Offset        float64                `protobuf:"fixed64,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRangeAndWeightOffset) Reset() {
	*x = StatRangeAndWeightOffset{}
	mi := &file_weights_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRangeAndWeightOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRangeAndWeightOffset) ProtoMessage() {}

func (x *StatRangeAndWeightOffset) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRangeAndWeightOffset.ProtoReflect.Descriptor instead.
func (*StatRangeAndWeightOffset) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{8}
}

func (x *StatRangeAndWeightOffset) GetStatMinimum() uint32 {
	if x != nil {
		return x.StatMinimum
	}
	return 0
}

func (x *StatRangeAndWeightOffset) GetStatMaximum() uint32 {
	if x != nil {
		return x.StatMaximum
	}
	return 0
}

func (x *StatRangeAndWeightOffset) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *StatRangeAndWeightOffset) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type StatTypeAndStatRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=gearproto.StatType" json:"stat_type,omitempty"`
	StatMinimum   uint32                 `protobuf:"varint,2,opt,name=stat_minimum,json=statMinimum,proto3" json:"stat_minimum,omitempty"`
	StatMaximum   uint32                 `protobuf:"varint,3,opt,name=stat_maximum,json=statMaximum,proto3" json:"stat_maximum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatTypeAndStatRange) Reset() {
	*x = StatTypeAndStatRange{}
	mi := &file_weights_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatTypeAndStatRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatTypeAndStatRange) ProtoMessage() {}

func (x *StatTypeAndStatRange) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatTypeAndStatRange.ProtoReflect.Descriptor instead.
func (*StatTypeAndStatRange) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{9}
}

func (x *StatTypeAndStatRange) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_StatType_Unknown
}

func (x *StatTypeAndStatRange) GetStatMinimum() uint32 {
	if x != nil {
		return x.StatMinimum
	}
	return 0
}

func (x *StatTypeAndStatRange) GetStatMaximum() uint32 {
	if x != nil {
		return x.StatMaximum
	}
	return 0
}

type SimTypeAndSimRatio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimType       SimType                `protobuf:"varint,1,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	RatioScale    uint32                 `protobuf:"varint,2,opt,name=ratio_scale,json=ratioScale,proto3" json:"ratio_scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimTypeAndSimRatio) Reset() {
	*x = SimTypeAndSimRatio{}
	mi := &file_weights_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimTypeAndSimRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimTypeAndSimRatio) ProtoMessage() {}

func (x *SimTypeAndSimRatio) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimTypeAndSimRatio.ProtoReflect.Descriptor instead.
func (*SimTypeAndSimRatio) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{10}
}

func (x *SimTypeAndSimRatio) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_SimType_Unknown
}

func (x *SimTypeAndSimRatio) GetRatioScale() uint32 {
	if x != nil {
		return x.RatioScale
	}
	return 0
}

type SimTypeAndScaleOffset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimType       SimType                `protobuf:"varint,1,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	Scale         float64                `protobuf:"fixed64,2,opt,name=scale,proto3" json:"scale,omitempty"`
	Offset        float64                `protobuf:"fixed64,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimTypeAndScaleOffset) Reset() {
	*x = SimTypeAndScaleOffset{}
	mi := &file_weights_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimTypeAndScaleOffset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimTypeAndScaleOffset) ProtoMessage() {}

func (x *SimTypeAndScaleOffset) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimTypeAndScaleOffset.ProtoReflect.Descriptor instead.
func (*SimTypeAndScaleOffset) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{11}
}

func (x *SimTypeAndScaleOffset) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_SimType_Unknown
}

func (x *SimTypeAndScaleOffset) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *SimTypeAndScaleOffset) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SimTypeAndScaleOffsetAndSimRatio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimType       SimType                `protobuf:"varint,1,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	RangingScale  float64                `protobuf:"fixed64,2,opt,name=ranging_scale,json=rangingScale,proto3" json:"ranging_scale,omitempty"`
	RangingOffset float64                `protobuf:"fixed64,3,opt,name=ranging_offset,json=rangingOffset,proto3" json:"ranging_offset,omitempty"`
	RatioScale    float64                `protobuf:"fixed64,4,opt,name=ratio_scale,json=ratioScale,proto3" json:"ratio_scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimTypeAndScaleOffsetAndSimRatio) Reset() {
	*x = SimTypeAndScaleOffsetAndSimRatio{}
	mi := &file_weights_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimTypeAndScaleOffsetAndSimRatio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimTypeAndScaleOffsetAndSimRatio) ProtoMessage() {}

func (x *SimTypeAndScaleOffsetAndSimRatio) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimTypeAndScaleOffsetAndSimRatio.ProtoReflect.Descriptor instead.
func (*SimTypeAndScaleOffsetAndSimRatio) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{12}
}

func (x *SimTypeAndScaleOffsetAndSimRatio) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_SimType_Unknown
}

func (x *SimTypeAndScaleOffsetAndSimRatio) GetRangingScale() float64 {
	if x != nil {
		return x.RangingScale
	}
	return 0
}

func (x *SimTypeAndScaleOffsetAndSimRatio) GetRangingOffset() float64 {
	if x != nil {
		return x.RangingOffset
	}
	return 0
}

func (x *SimTypeAndScaleOffsetAndSimRatio) GetRatioScale() float64 {
	if x != nil {
		return x.RatioScale
	}
	return 0
}

var File_weights_proto protoreflect.FileDescriptor

const file_weights_proto_rawDesc = "" +
	"\n" +
	"\rweights.proto\x12\tgearproto\x1a\x11gear-common.proto\"\xcd\x01\n" +
	"\aWeight1\x12\x1e\n" +
	"\n" +
	"weightType\x18\x01 \x01(\x05R\n" +
	"weightType\x129\n" +
	"\x06weight\x18\x02 \x03(\v2!.gearproto.StatTypeAndFloatWeightR\x06weight\x129\n" +
	"\bpriority\x18\x03 \x03(\v2\x1d.gearproto.SimTypeAndSimRatioR\bpriority\x12\x14\n" +
	"\x05scale\x18\x04 \x01(\x01R\x05scale\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x01R\x06offset\"\xb3\x01\n" +
	"\aWeight2\x12\x1e\n" +
	"\n" +
	"weightType\x18\x01 \x01(\x05R\n" +
	"weightType\x12?\n" +
	"\aweights\x18\x02 \x03(\v2%.gearproto.StatSimTypesAndFloatWeightR\aweights\x12G\n" +
	"\bpriority\x18\x03 \x03(\v2+.gearproto.SimTypeAndScaleOffsetAndSimRatioR\bpriority\"\xb5\x01\n" +
	"\aWeight3\x12\x1e\n" +
	"\n" +
	"weightType\x18\x01 \x01(\x05R\n" +
	"weightType\x12A\n" +
	"\aweights\x18\x02 \x03(\v2'.gearproto.StatSimTypesAndNestedEntriesR\aweights\x12G\n" +
	"\bpriority\x18\x03 \x03(\v2+.gearproto.SimTypeAndScaleOffsetAndSimRatioR\bpriority\"\x9b\x01\n" +
	"\aWeight4\x12\x1e\n" +
	"\n" +
	"weightType\x18\x01 \x01(\x05R\n" +
	"weightType\x125\n" +
	"\bsegments\x18\x02 \x03(\v2\x19.gearproto.Weight4SegmentR\bsegments\x129\n" +
	"\bpriority\x18\x03 \x03(\v2\x1d.gearproto.SimTypeAndSimRatioR\bpriority\"\xc4\x01\n" +
	"\x0eWeight4Segment\x125\n" +
	"\x05bound\x18\x01 \x03(\v2\x1f.gearproto.StatTypeAndStatRangeR\x05bound\x12?\n" +
	"\aweights\x18\x02 \x03(\v2%.gearproto.StatSimTypesAndFloatWeightR\aweights\x12:\n" +
	"\aoffsets\x18\x03 \x03(\v2 .gearproto.SimTypeAndScaleOffsetR\aoffsets\"b\n" +
	"\x16StatTypeAndFloatWeight\x120\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\"\x95\x01\n" +
	"\x1aStatSimTypesAndFloatWeight\x120\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12-\n" +
	"\bsim_type\x18\x02 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\"\xbe\x01\n" +
	"\x1cStatSimTypesAndNestedEntries\x120\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12-\n" +
	"\bsim_type\x18\x02 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12=\n" +
	"\aentries\x18\x03 \x03(\v2#.gearproto.StatRangeAndWeightOffsetR\aentries\"\x90\x01\n" +
	"\x18StatRangeAndWeightOffset\x12!\n" +
	"\fstat_minimum\x18\x01 \x01(\rR\vstatMinimum\x12!\n" +
	"\fstat_maximum\x18\x02 \x01(\rR\vstatMaximum\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x01R\x06offset\"\x8e\x01\n" +
	"\x14StatTypeAndStatRange\x120\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12!\n" +
	"\fstat_minimum\x18\x02 \x01(\rR\vstatMinimum\x12!\n" +
	"\fstat_maximum\x18\x03 \x01(\rR\vstatMaximum\"d\n" +
	"\x12SimTypeAndSimRatio\x12-\n" +
	"\bsim_type\x18\x01 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12\x1f\n" +
	"\vratio_scale\x18\x02 \x01(\rR\n" +
	"ratioScale\"t\n" +
	"\x15SimTypeAndScaleOffset\x12-\n" +
	"\bsim_type\x18\x01 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12\x14\n" +
	"\x05scale\x18\x02 \x01(\x01R\x05scale\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x01R\x06offset\"\xbe\x01\n" +
	" SimTypeAndScaleOffsetAndSimRatio\x12-\n" +
	"\bsim_type\x18\x01 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12#\n" +
	"\rranging_scale\x18\x02 \x01(\x01R\frangingScale\x12%\n" +
	"\x0eranging_offset\x18\x03 \x01(\x01R\rrangingOffset\x12\x1f\n" +
	"\vratio_scale\x18\x04 \x01(\x01R\n" +
	"ratioScaleB\rZ\v./gearprotob\x06proto3"

var (
	file_weights_proto_rawDescOnce sync.Once
	file_weights_proto_rawDescData []byte
)

func file_weights_proto_rawDescGZIP() []byte {
	file_weights_proto_rawDescOnce.Do(func() {
		file_weights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weights_proto_rawDesc), len(file_weights_proto_rawDesc)))
	})
	return file_weights_proto_rawDescData
}

var file_weights_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_weights_proto_goTypes = []any{
	(*Weight1)(nil),                          // 0: gearproto.Weight1
	(*Weight2)(nil),                          // 1: gearproto.Weight2
	(*Weight3)(nil),                          // 2: gearproto.Weight3
	(*Weight4)(nil),                          // 3: gearproto.Weight4
	(*Weight4Segment)(nil),                   // 4: gearproto.Weight4Segment
	(*StatTypeAndFloatWeight)(nil),           // 5: gearproto.StatTypeAndFloatWeight
	(*StatSimTypesAndFloatWeight)(nil),       // 6: gearproto.StatSimTypesAndFloatWeight
	(*StatSimTypesAndNestedEntries)(nil),     // 7: gearproto.StatSimTypesAndNestedEntries
	(*StatRangeAndWeightOffset)(nil),         // 8: gearproto.StatRangeAndWeightOffset
	(*StatTypeAndStatRange)(nil),             // 9: gearproto.StatTypeAndStatRange
	(*SimTypeAndSimRatio)(nil),               // 10: gearproto.SimTypeAndSimRatio
	(*SimTypeAndScaleOffset)(nil),            // 11: gearproto.SimTypeAndScaleOffset
	(*SimTypeAndScaleOffsetAndSimRatio)(nil), // 12: gearproto.SimTypeAndScaleOffsetAndSimRatio
	(StatType)(0),                            // 13: gearproto.StatType
	(SimType)(0),                             // 14: gearproto.SimType
}
var file_weights_proto_depIdxs = []int32{
	5,  // 0: gearproto.Weight1.weight:type_name -> gearproto.StatTypeAndFloatWeight
	10, // 1: gearproto.Weight1.priority:type_name -> gearproto.SimTypeAndSimRatio
	6,  // 2: gearproto.Weight2.weights:type_name -> gearproto.StatSimTypesAndFloatWeight
	12, // 3: gearproto.Weight2.priority:type_name -> gearproto.SimTypeAndScaleOffsetAndSimRatio
	7,  // 4: gearproto.Weight3.weights:type_name -> gearproto.StatSimTypesAndNestedEntries
	12, // 5: gearproto.Weight3.priority:type_name -> gearproto.SimTypeAndScaleOffsetAndSimRatio
	4,  // 6: gearproto.Weight4.segments:type_name -> gearproto.Weight4Segment
	10, // 7: gearproto.Weight4.priority:type_name -> gearproto.SimTypeAndSimRatio
	9,  // 8: gearproto.Weight4Segment.bound:type_name -> gearproto.StatTypeAndStatRange
	6,  // 9: gearproto.Weight4Segment.weights:type_name -> gearproto.StatSimTypesAndFloatWeight
	11, // 10: gearproto.Weight4Segment.offsets:type_name -> gearproto.SimTypeAndScaleOffset
	13, // 11: gearproto.StatTypeAndFloatWeight.stat_type:type_name -> gearproto.StatType
	13, // 12: gearproto.StatSimTypesAndFloatWeight.stat_type:type_name -> gearproto.StatType
	14, // 13: gearproto.StatSimTypesAndFloatWeight.sim_type:type_name -> gearproto.SimType
	13, // 14: gearproto.StatSimTypesAndNestedEntries.stat_type:type_name -> gearproto.StatType
	14, // 15: gearproto.StatSimTypesAndNestedEntries.sim_type:type_name -> gearproto.SimType
	8,  // 16: gearproto.StatSimTypesAndNestedEntries.entries:type_name -> gearproto.StatRangeAndWeightOffset
	13, // 17: gearproto.StatTypeAndStatRange.stat_type:type_name -> gearproto.StatType
	14, // 18: gearproto.SimTypeAndSimRatio.sim_type:type_name -> gearproto.SimType
	14, // 19: gearproto.SimTypeAndScaleOffset.sim_type:type_name -> gearproto.SimType
	14, // 20: gearproto.SimTypeAndScaleOffsetAndSimRatio.sim_type:type_name -> gearproto.SimType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_weights_proto_init() }
func file_weights_proto_init() {
	if File_weights_proto != nil {
		return
	}
	file_gear_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weights_proto_rawDesc), len(file_weights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weights_proto_goTypes,
		DependencyIndexes: file_weights_proto_depIdxs,
		MessageInfos:      file_weights_proto_msgTypes,
	}.Build()
	File_weights_proto = out.File
	file_weights_proto_goTypes = nil
	file_weights_proto_depIdxs = nil
}
