// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: gear-common.proto

package gearproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatType int32

const (
	StatType_Strength  StatType = 0
	StatType_Agility   StatType = 1
	StatType_Stamina   StatType = 2
	StatType_Intellect StatType = 3
	StatType_Spirit    StatType = 4
	StatType_Hit       StatType = 5
	StatType_Crit      StatType = 6
	StatType_Haste     StatType = 7
	StatType_Expertise StatType = 8
	StatType_Dodge     StatType = 9
	StatType_Parry     StatType = 10
	StatType_Mastery   StatType = 11
)

// Enum value maps for StatType.
var (
	StatType_name = map[int32]string{
		0:  "Strength",
		1:  "Agility",
		2:  "Stamina",
		3:  "Intellect",
		4:  "Spirit",
		5:  "Hit",
		6:  "Crit",
		7:  "Haste",
		8:  "Expertise",
		9:  "Dodge",
		10: "Parry",
		11: "Mastery",
	}
	StatType_value = map[string]int32{
		"Strength":  0,
		"Agility":   1,
		"Stamina":   2,
		"Intellect": 3,
		"Spirit":    4,
		"Hit":       5,
		"Crit":      6,
		"Haste":     7,
		"Expertise": 8,
		"Dodge":     9,
		"Parry":     10,
		"Mastery":   11,
	}
)

func (x StatType) Enum() *StatType {
	p := new(StatType)
	*p = x
	return p
}

func (x StatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatType) Descriptor() protoreflect.EnumDescriptor {
	return file_gear_common_proto_enumTypes[0].Descriptor()
}

func (StatType) Type() protoreflect.EnumType {
	return &file_gear_common_proto_enumTypes[0]
}

func (x StatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatType.Descriptor instead.
func (StatType) EnumDescriptor() ([]byte, []int) {
	return file_gear_common_proto_rawDescGZIP(), []int{0}
}

var File_gear_common_proto protoreflect.FileDescriptor

const file_gear_common_proto_rawDesc = "" +
	"\n" +
	"\x11gear-common.proto\x12\tgearproto*\x9d\x01\n" +
	"\bStatType\x12\f\n" +
	"\bStrength\x10\x00\x12\v\n" +
	"\aAgility\x10\x01\x12\v\n" +
	"\aStamina\x10\x02\x12\r\n" +
	"\tIntellect\x10\x03\x12\n" +
	"\n" +
	"\x06Spirit\x10\x04\x12\a\n" +
	"\x03Hit\x10\x05\x12\b\n" +
	"\x04Crit\x10\x06\x12\t\n" +
	"\x05Haste\x10\a\x12\r\n" +
	"\tExpertise\x10\b\x12\t\n" +
	"\x05Dodge\x10\t\x12\t\n" +
	"\x05Parry\x10\n" +
	"\x12\v\n" +
	"\aMastery\x10\vB\rZ\v./gearprotob\x06proto3"

var (
	file_gear_common_proto_rawDescOnce sync.Once
	file_gear_common_proto_rawDescData []byte
)

func file_gear_common_proto_rawDescGZIP() []byte {
	file_gear_common_proto_rawDescOnce.Do(func() {
		file_gear_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gear_common_proto_rawDesc), len(file_gear_common_proto_rawDesc)))
	})
	return file_gear_common_proto_rawDescData
}

var file_gear_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gear_common_proto_goTypes = []any{
	(StatType)(0), // 0: gearproto.StatType
}
var file_gear_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gear_common_proto_init() }
func file_gear_common_proto_init() {
	if File_gear_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gear_common_proto_rawDesc), len(file_gear_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gear_common_proto_goTypes,
		DependencyIndexes: file_gear_common_proto_depIdxs,
		EnumInfos:         file_gear_common_proto_enumTypes,
	}.Build()
	File_gear_common_proto = out.File
	file_gear_common_proto_goTypes = nil
	file_gear_common_proto_depIdxs = nil
}
