syntax = "proto3";
package gearproto;

option go_package = "./gearproto";

import "gear-common.proto";

message MultiSetJob {
  int32 simRunSize = 1;
  repeated MultiSetParam param = 2;
  repeated FixedForge fixed_forge = 3;
  repeated DistinctUsageGroups usage_groups = 4;
  string bagsFile = 5;
}

message MultiSetParam {
  string Label = 1;
  string GearFile = 2;
  Model  Model = 3;

  double RatingPercent = 4;
  int32 ExtraUpgradeLevel = 6;
  int32 ForceUpgradeExistingItems = 7;

  bool ExtraFromBags = 8;
  repeated uint32 ExtraItems = 9;
  repeated uint32 BlockedItems = 10;

  repeated ItemInSlot ForceSingle = 11;
  repeated ItemListInSlot ForceTryAll = 12;
  ItemInSlot ReportVariant = 13;
}

message Model {
  StatRequirements  StatRequirements = 1;
  StatRatings       StatRatings = 2;
  SpecType          Spec = 3;
  OptimiseGoal      Goal = 4;
  Fight             Fight = 5;

  ReforgeRules      ReforgeRules = 6;
  repeated Enchant  Enchant = 7;
  repeated Gem      Gem = 8;
  Professions       Professions = 9;

  SetBonus          SetBonus = 10;
  uint32            SetBonusRequired = 11;
}

message StatRequirements {
  uint32 hitMin = 1;
  uint32 hitMax = 2;
  uint32 expMin = 3;
  uint32 expMax = 4;
  StatType additionalStat = 5;
  uint32 additionalValue = 6;
}

message StatRatings {
  // treat like a oneof, can't be due to repeated
  string pawnFile = 1;
  repeated StatType priority = 2;
  StatBlock values = 3;
}

message ReforgeRules {
  repeated StatType source = 1;
  repeated StatType target = 2;
}

message Enchant {
  SlotItem slot = 1;
  oneof specify {
    uint32 effectId = 2;
    string name = 3;
  }
}

message Gem {
  SocketType socket = 1;
  oneof specify {
    uint32 gemId = 2;
    StatBlock stats = 3;
  }
}

message Professions {
  bool IsBlacksmith = 1;
  bool IsEngineer = 2;
}

message SetBonus {
  // treat like a oneof, can't be due to repeated
  bool            none = 1;
  bool            specDefault = 2;
  repeated string named = 3;
}

message StatBlock {
  repeated StatValue values = 1;
}

message FixedForge {
  uint32 itemId = 1;
  bool default = 2;
  StatType from = 3;
  StatType to = 4;
}

message DistinctUsageGroups {
  uint32 itemId = 1;
  repeated string groupA = 2;
  repeated string groupB = 3;
}

message ItemInSlot {
  SlotEquip slot = 1;
  uint32 itemId = 2;
}

message ItemListInSlot {
  SlotEquip slot = 1;
  repeated uint32 itemId = 2;
}

message StatValue {
  StatType statType = 1;
  uint32 value = 2;
}

