// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: weights.proto

package gearproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimType int32

const (
	SimType_DPS   SimType = 0
	SimType_TPS   SimType = 1
	SimType_DTPS  SimType = 2
	SimType_HPS   SimType = 3
	SimType_TMI   SimType = 4
	SimType_DEATH SimType = 5
	SimType_TTO   SimType = 6
)

// Enum value maps for SimType.
var (
	SimType_name = map[int32]string{
		0: "DPS",
		1: "TPS",
		2: "DTPS",
		3: "HPS",
		4: "TMI",
		5: "DEATH",
		6: "TTO",
	}
	SimType_value = map[string]int32{
		"DPS":   0,
		"TPS":   1,
		"DTPS":  2,
		"HPS":   3,
		"TMI":   4,
		"DEATH": 5,
		"TTO":   6,
	}
)

func (x SimType) Enum() *SimType {
	p := new(SimType)
	*p = x
	return p
}

func (x SimType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimType) Descriptor() protoreflect.EnumDescriptor {
	return file_weights_proto_enumTypes[0].Descriptor()
}

func (SimType) Type() protoreflect.EnumType {
	return &file_weights_proto_enumTypes[0]
}

func (x SimType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimType.Descriptor instead.
func (SimType) EnumDescriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{0}
}

type Weight1Basic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        []*Weight1Entry        `protobuf:"bytes,1,rep,name=weight,proto3" json:"weight,omitempty"`
	Priority      []*Priority1Entry      `protobuf:"bytes,2,rep,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight1Basic) Reset() {
	*x = Weight1Basic{}
	mi := &file_weights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight1Basic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight1Basic) ProtoMessage() {}

func (x *Weight1Basic) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight1Basic.ProtoReflect.Descriptor instead.
func (*Weight1Basic) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{0}
}

func (x *Weight1Basic) GetWeight() []*Weight1Entry {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *Weight1Basic) GetPriority() []*Priority1Entry {
	if x != nil {
		return x.Priority
	}
	return nil
}

type Weight2Extended struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated StatType stat_type        = 1;
	// repeated SimType sim_type          = 2;
	Weights       []*Weight2Entry   `protobuf:"bytes,3,rep,name=weights,proto3" json:"weights,omitempty"`
	Priority      []*Priority2Entry `protobuf:"bytes,4,rep,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight2Extended) Reset() {
	*x = Weight2Extended{}
	mi := &file_weights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight2Extended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight2Extended) ProtoMessage() {}

func (x *Weight2Extended) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight2Extended.ProtoReflect.Descriptor instead.
func (*Weight2Extended) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{1}
}

func (x *Weight2Extended) GetWeights() []*Weight2Entry {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *Weight2Extended) GetPriority() []*Priority2Entry {
	if x != nil {
		return x.Priority
	}
	return nil
}

type Weight3Extended struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated StatType stat_type        = 1;
	// repeated SimType sim_type          = 2;
	Weights       []*Weight3Group   `protobuf:"bytes,3,rep,name=weights,proto3" json:"weights,omitempty"`
	Priority      []*Priority2Entry `protobuf:"bytes,4,rep,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight3Extended) Reset() {
	*x = Weight3Extended{}
	mi := &file_weights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight3Extended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight3Extended) ProtoMessage() {}

func (x *Weight3Extended) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight3Extended.ProtoReflect.Descriptor instead.
func (*Weight3Extended) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{2}
}

func (x *Weight3Extended) GetWeights() []*Weight3Group {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *Weight3Extended) GetPriority() []*Priority2Entry {
	if x != nil {
		return x.Priority
	}
	return nil
}

type Weight1Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=gearproto.StatType" json:"stat_type,omitempty"`
	RatingWeight  uint32                 `protobuf:"varint,2,opt,name=rating_weight,json=ratingWeight,proto3" json:"rating_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight1Entry) Reset() {
	*x = Weight1Entry{}
	mi := &file_weights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight1Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight1Entry) ProtoMessage() {}

func (x *Weight1Entry) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight1Entry.ProtoReflect.Descriptor instead.
func (*Weight1Entry) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{3}
}

func (x *Weight1Entry) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_Strength
}

func (x *Weight1Entry) GetRatingWeight() uint32 {
	if x != nil {
		return x.RatingWeight
	}
	return 0
}

type Weight2Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=gearproto.StatType" json:"stat_type,omitempty"`
	SimType       SimType                `protobuf:"varint,2,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	RatingWeight  float64                `protobuf:"fixed64,3,opt,name=rating_weight,json=ratingWeight,proto3" json:"rating_weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight2Entry) Reset() {
	*x = Weight2Entry{}
	mi := &file_weights_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight2Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight2Entry) ProtoMessage() {}

func (x *Weight2Entry) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight2Entry.ProtoReflect.Descriptor instead.
func (*Weight2Entry) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{4}
}

func (x *Weight2Entry) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_Strength
}

func (x *Weight2Entry) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_DPS
}

func (x *Weight2Entry) GetRatingWeight() float64 {
	if x != nil {
		return x.RatingWeight
	}
	return 0
}

type Weight3Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatType      StatType               `protobuf:"varint,1,opt,name=stat_type,json=statType,proto3,enum=gearproto.StatType" json:"stat_type,omitempty"`
	SimType       SimType                `protobuf:"varint,2,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	Entries       []*Weight3Entry        `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight3Group) Reset() {
	*x = Weight3Group{}
	mi := &file_weights_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight3Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight3Group) ProtoMessage() {}

func (x *Weight3Group) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight3Group.ProtoReflect.Descriptor instead.
func (*Weight3Group) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{5}
}

func (x *Weight3Group) GetStatType() StatType {
	if x != nil {
		return x.StatType
	}
	return StatType_Strength
}

func (x *Weight3Group) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_DPS
}

func (x *Weight3Group) GetEntries() []*Weight3Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Weight3Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatRange     *StatRange             `protobuf:"bytes,1,opt,name=stat_range,json=statRange,proto3" json:"stat_range,omitempty"`
	RatingWeight  float64                `protobuf:"fixed64,2,opt,name=rating_weight,json=ratingWeight,proto3" json:"rating_weight,omitempty"`
	RatingOffset  float64                `protobuf:"fixed64,3,opt,name=rating_offset,json=ratingOffset,proto3" json:"rating_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weight3Entry) Reset() {
	*x = Weight3Entry{}
	mi := &file_weights_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weight3Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weight3Entry) ProtoMessage() {}

func (x *Weight3Entry) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weight3Entry.ProtoReflect.Descriptor instead.
func (*Weight3Entry) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{6}
}

func (x *Weight3Entry) GetStatRange() *StatRange {
	if x != nil {
		return x.StatRange
	}
	return nil
}

func (x *Weight3Entry) GetRatingWeight() float64 {
	if x != nil {
		return x.RatingWeight
	}
	return 0
}

func (x *Weight3Entry) GetRatingOffset() float64 {
	if x != nil {
		return x.RatingOffset
	}
	return 0
}

type StatRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Minimum       uint32                 `protobuf:"varint,1,opt,name=Minimum,proto3" json:"Minimum,omitempty"`
	Maximum       uint32                 `protobuf:"varint,2,opt,name=Maximum,proto3" json:"Maximum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRange) Reset() {
	*x = StatRange{}
	mi := &file_weights_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRange) ProtoMessage() {}

func (x *StatRange) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRange.ProtoReflect.Descriptor instead.
func (*StatRange) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{7}
}

func (x *StatRange) GetMinimum() uint32 {
	if x != nil {
		return x.Minimum
	}
	return 0
}

func (x *StatRange) GetMaximum() uint32 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

type Priority1Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimType       SimType                `protobuf:"varint,1,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	RatioScale    uint32                 `protobuf:"varint,2,opt,name=ratio_scale,json=ratioScale,proto3" json:"ratio_scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Priority1Entry) Reset() {
	*x = Priority1Entry{}
	mi := &file_weights_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Priority1Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Priority1Entry) ProtoMessage() {}

func (x *Priority1Entry) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Priority1Entry.ProtoReflect.Descriptor instead.
func (*Priority1Entry) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{8}
}

func (x *Priority1Entry) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_DPS
}

func (x *Priority1Entry) GetRatioScale() uint32 {
	if x != nil {
		return x.RatioScale
	}
	return 0
}

type Priority2Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SimType       SimType                `protobuf:"varint,1,opt,name=sim_type,json=simType,proto3,enum=gearproto.SimType" json:"sim_type,omitempty"`
	RangingScale  float64                `protobuf:"fixed64,2,opt,name=ranging_scale,json=rangingScale,proto3" json:"ranging_scale,omitempty"`
	RangingOffset float64                `protobuf:"fixed64,3,opt,name=ranging_offset,json=rangingOffset,proto3" json:"ranging_offset,omitempty"`
	RatioScale    float64                `protobuf:"fixed64,4,opt,name=ratio_scale,json=ratioScale,proto3" json:"ratio_scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Priority2Entry) Reset() {
	*x = Priority2Entry{}
	mi := &file_weights_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Priority2Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Priority2Entry) ProtoMessage() {}

func (x *Priority2Entry) ProtoReflect() protoreflect.Message {
	mi := &file_weights_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Priority2Entry.ProtoReflect.Descriptor instead.
func (*Priority2Entry) Descriptor() ([]byte, []int) {
	return file_weights_proto_rawDescGZIP(), []int{9}
}

func (x *Priority2Entry) GetSimType() SimType {
	if x != nil {
		return x.SimType
	}
	return SimType_DPS
}

func (x *Priority2Entry) GetRangingScale() float64 {
	if x != nil {
		return x.RangingScale
	}
	return 0
}

func (x *Priority2Entry) GetRangingOffset() float64 {
	if x != nil {
		return x.RangingOffset
	}
	return 0
}

func (x *Priority2Entry) GetRatioScale() float64 {
	if x != nil {
		return x.RatioScale
	}
	return 0
}

var File_weights_proto protoreflect.FileDescriptor

const file_weights_proto_rawDesc = "" +
	"\n" +
	"\rweights.proto\x12\tgearproto\x1a\x11gear-common.proto\"v\n" +
	"\fWeight1Basic\x12/\n" +
	"\x06weight\x18\x01 \x03(\v2\x17.gearproto.Weight1EntryR\x06weight\x125\n" +
	"\bpriority\x18\x02 \x03(\v2\x19.gearproto.Priority1EntryR\bpriority\"{\n" +
	"\x0fWeight2Extended\x121\n" +
	"\aweights\x18\x03 \x03(\v2\x17.gearproto.Weight2EntryR\aweights\x125\n" +
	"\bpriority\x18\x04 \x03(\v2\x19.gearproto.Priority2EntryR\bpriority\"{\n" +
	"\x0fWeight3Extended\x121\n" +
	"\aweights\x18\x03 \x03(\v2\x17.gearproto.Weight3GroupR\aweights\x125\n" +
	"\bpriority\x18\x04 \x03(\v2\x19.gearproto.Priority2EntryR\bpriority\"e\n" +
	"\fWeight1Entry\x120\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12#\n" +
	"\rrating_weight\x18\x02 \x01(\rR\fratingWeight\"\x94\x01\n" +
	"\fWeight2Entry\x120\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12-\n" +
	"\bsim_type\x18\x02 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12#\n" +
	"\rrating_weight\x18\x03 \x01(\x01R\fratingWeight\"\xa2\x01\n" +
	"\fWeight3Group\x120\n" +
	"\tstat_type\x18\x01 \x01(\x0e2\x13.gearproto.StatTypeR\bstatType\x12-\n" +
	"\bsim_type\x18\x02 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x121\n" +
	"\aentries\x18\x03 \x03(\v2\x17.gearproto.Weight3EntryR\aentries\"\x8d\x01\n" +
	"\fWeight3Entry\x123\n" +
	"\n" +
	"stat_range\x18\x01 \x01(\v2\x14.gearproto.StatRangeR\tstatRange\x12#\n" +
	"\rrating_weight\x18\x02 \x01(\x01R\fratingWeight\x12#\n" +
	"\rrating_offset\x18\x03 \x01(\x01R\fratingOffset\"?\n" +
	"\tStatRange\x12\x18\n" +
	"\aMinimum\x18\x01 \x01(\rR\aMinimum\x12\x18\n" +
	"\aMaximum\x18\x02 \x01(\rR\aMaximum\"`\n" +
	"\x0ePriority1Entry\x12-\n" +
	"\bsim_type\x18\x01 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12\x1f\n" +
	"\vratio_scale\x18\x02 \x01(\rR\n" +
	"ratioScale\"\xac\x01\n" +
	"\x0ePriority2Entry\x12-\n" +
	"\bsim_type\x18\x01 \x01(\x0e2\x12.gearproto.SimTypeR\asimType\x12#\n" +
	"\rranging_scale\x18\x02 \x01(\x01R\frangingScale\x12%\n" +
	"\x0eranging_offset\x18\x03 \x01(\x01R\rrangingOffset\x12\x1f\n" +
	"\vratio_scale\x18\x04 \x01(\x01R\n" +
	"ratioScale*K\n" +
	"\aSimType\x12\a\n" +
	"\x03DPS\x10\x00\x12\a\n" +
	"\x03TPS\x10\x01\x12\b\n" +
	"\x04DTPS\x10\x02\x12\a\n" +
	"\x03HPS\x10\x03\x12\a\n" +
	"\x03TMI\x10\x04\x12\t\n" +
	"\x05DEATH\x10\x05\x12\a\n" +
	"\x03TTO\x10\x06B\rZ\v./gearprotob\x06proto3"

var (
	file_weights_proto_rawDescOnce sync.Once
	file_weights_proto_rawDescData []byte
)

func file_weights_proto_rawDescGZIP() []byte {
	file_weights_proto_rawDescOnce.Do(func() {
		file_weights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weights_proto_rawDesc), len(file_weights_proto_rawDesc)))
	})
	return file_weights_proto_rawDescData
}

var file_weights_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_weights_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_weights_proto_goTypes = []any{
	(SimType)(0),            // 0: gearproto.SimType
	(*Weight1Basic)(nil),    // 1: gearproto.Weight1Basic
	(*Weight2Extended)(nil), // 2: gearproto.Weight2Extended
	(*Weight3Extended)(nil), // 3: gearproto.Weight3Extended
	(*Weight1Entry)(nil),    // 4: gearproto.Weight1Entry
	(*Weight2Entry)(nil),    // 5: gearproto.Weight2Entry
	(*Weight3Group)(nil),    // 6: gearproto.Weight3Group
	(*Weight3Entry)(nil),    // 7: gearproto.Weight3Entry
	(*StatRange)(nil),       // 8: gearproto.StatRange
	(*Priority1Entry)(nil),  // 9: gearproto.Priority1Entry
	(*Priority2Entry)(nil),  // 10: gearproto.Priority2Entry
	(StatType)(0),           // 11: gearproto.StatType
}
var file_weights_proto_depIdxs = []int32{
	4,  // 0: gearproto.Weight1Basic.weight:type_name -> gearproto.Weight1Entry
	9,  // 1: gearproto.Weight1Basic.priority:type_name -> gearproto.Priority1Entry
	5,  // 2: gearproto.Weight2Extended.weights:type_name -> gearproto.Weight2Entry
	10, // 3: gearproto.Weight2Extended.priority:type_name -> gearproto.Priority2Entry
	6,  // 4: gearproto.Weight3Extended.weights:type_name -> gearproto.Weight3Group
	10, // 5: gearproto.Weight3Extended.priority:type_name -> gearproto.Priority2Entry
	11, // 6: gearproto.Weight1Entry.stat_type:type_name -> gearproto.StatType
	11, // 7: gearproto.Weight2Entry.stat_type:type_name -> gearproto.StatType
	0,  // 8: gearproto.Weight2Entry.sim_type:type_name -> gearproto.SimType
	11, // 9: gearproto.Weight3Group.stat_type:type_name -> gearproto.StatType
	0,  // 10: gearproto.Weight3Group.sim_type:type_name -> gearproto.SimType
	7,  // 11: gearproto.Weight3Group.entries:type_name -> gearproto.Weight3Entry
	8,  // 12: gearproto.Weight3Entry.stat_range:type_name -> gearproto.StatRange
	0,  // 13: gearproto.Priority1Entry.sim_type:type_name -> gearproto.SimType
	0,  // 14: gearproto.Priority2Entry.sim_type:type_name -> gearproto.SimType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_weights_proto_init() }
func file_weights_proto_init() {
	if File_weights_proto != nil {
		return
	}
	file_gear_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weights_proto_rawDesc), len(file_weights_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weights_proto_goTypes,
		DependencyIndexes: file_weights_proto_depIdxs,
		EnumInfos:         file_weights_proto_enumTypes,
		MessageInfos:      file_weights_proto_msgTypes,
	}.Build()
	File_weights_proto = out.File
	file_weights_proto_goTypes = nil
	file_weights_proto_depIdxs = nil
}
